version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiafinal_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: hia
      DB_PORT: 5432
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/hia"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: hiafinal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hia
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=log"
      - "-c"
      - "log_filename=postgresql.log"
      - "-c"
      - "log_statement=all"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: hiafinal_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  db_backup:
    image: postgres:15
    container_name: hiafinal_backup
    volumes:
      - ./backups:/backups
    environment:
      PGPASSWORD: postgres
    entrypoint: >
      bash -c "while true; do
        pg_dump -h db -U postgres hia > /backups/backup_$(date +%Y%m%d_%H%M%S).sql;
        echo 'Backup generado';
        sleep 86400;
      done"
    depends_on:
      - db
    restart: unless-stopped

  pgbadger:
    image: dalibo/pgbadger
    container_name: hiafinal_pgbadger
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgbadger_reports:/out
      - ./pgbadger/run.sh:/run.sh
    entrypoint: ["/bin/sh", "/run.sh"]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: hiafinal_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: hiafinal_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/hia?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    restart: unless-stopped 

  grafana:
    image: grafana/grafana:latest
    container_name: hiafinal_grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  mariadb_glpi:
    image: mariadb:10.6
    container_name: hiafinal_mariadb_glpi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - glpi_mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  glpi:
    image: diouxx/glpi
    container_name: hiafinal_glpi
    ports:
      - "8082:80"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - mariadb_glpi
    volumes:
      - glpi_data:/var/www/html/glpi
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  glpi_mariadb_data:
  glpi_data: