global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "hia_app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]