global:
  scrape_interval: 5s # cada 5 segundos, suficiente para el TP

scrape_configs:
  - job_name: "hia_app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
